In [1]:
from collections import OrderedDict
import numpy as np
import pandas as pd


from sklearn import neighbors
from sklearn import naive_bayes

In [20]:
from sklearn.datasets import load_iris


In [122]:
data = load_iris()

In [124]:
df = pd.DataFrame(data.data)

In [130]:
df.to_records(index=False).shape

(150,)

In [133]:
x = np.array([(1,2.,'Hello'), (2,3.,"World")], dtype=[('foo', 'i4'),('bar', 'f4'), ('baz', 'S10')])

In [138]:
x['foo']

array([1, 2], dtype=int32)

In [132]:
X['one']

array([[ 2.318,  2.727,  4.26 ,  7.212,  4.792],
       [ 2.315,  2.726,  4.295,  7.14 ,  4.783],
       [ 2.315,  2.724,  4.26 ,  7.135,  4.779],
       [ 2.11 ,  3.609,  4.33 ,  7.985,  5.595],
       [ 2.11 ,  3.626,  4.33 ,  8.203,  5.621],
       [ 2.11 ,  3.62 ,  4.47 ,  8.21 ,  5.612]])

In [111]:
X_named

array([[( 2.318,), ( 2.727,), ( 4.26 ,), ( 7.212,), ( 4.792,)],
       [( 2.315,), ( 2.726,), ( 4.295,), ( 7.14 ,), ( 4.783,)],
       [( 2.315,), ( 2.724,), ( 4.26 ,), ( 7.135,), ( 4.779,)],
       [( 2.11 ,), ( 3.609,), ( 4.33 ,), ( 7.985,), ( 5.595,)],
       [( 2.11 ,), ( 3.626,), ( 4.33 ,), ( 8.203,), ( 5.621,)],
       [( 2.11 ,), ( 3.62 ,), ( 4.47 ,), ( 8.21 ,), ( 5.612,)]], 
      dtype=[('one', '<f8')])

In [109]:
d.copy()

array([[ 2.318,  2.727,  4.26 ,  7.212,  4.792],
       [ 2.315,  2.726,  4.295,  7.14 ,  4.783],
       [ 2.315,  2.724,  4.26 ,  7.135,  4.779],
       [ 2.11 ,  3.609,  4.33 ,  7.985,  5.595],
       [ 2.11 ,  3.626,  4.33 ,  8.203,  5.621],
       [ 2.11 ,  3.62 ,  4.47 ,  8.21 ,  5.612]])

In [83]:
step_size = .0025

In [97]:
iris_data = datasets.load_iris()
X = np.array(iris_data.data, dtype=[('sepal_length', '<f8'), ('sepal_width', '<f8'), ('petal_length', '<f8'), ('petal_width', '<f8')])
# X = X.astype(dtype=[('sepal_length', '<f8'), ('sepal_width', '<f8'), ('petal_length', '<f8'), ('petal_width', '<f8')])

# y = iris_data.target
       
X.shape

(150, 4)

In [98]:
X_selected = X[['sepal_length', 'sepal_width']]
# raise Exception(X_selected.shape)
X_two_cols = X_selected.view(np.float64).reshape(len(X_selected), -1)

/usr/local/var/pyenv/versions/3.5.2/envs/yb-dev/lib/python3.5/site-packages/ipykernel_launcher.py:3: FutureWarning: Numpy has detected that you may be viewing or writing to an array returned by selecting multiple fields in a structured array. 

This code may break in numpy 1.13 because this will return a view instead of a copy -- see release notes for details.
  This is separate from the ipykernel package so we can avoid doing imports until


In [99]:
X_selected.shape

(150, 4)

In [100]:
X_two_cols.shape

(150, 8)

In [85]:
y.shape

(150,)

In [84]:
X = X_two_cols
model = naive_bayes.MultinomialNB()
model.fit(X, y)

# Plot the decision boundary. For that, we will assign a color to each
# point in the mesh [x_min, x_max]x[y_min, y_max].
x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1

# set the step increment for drawing the boundary graph
x_step = (x_max - x_min) * step_size
y_step = (y_max - y_min) * step_size

xx, yy = np.meshgrid(
    np.arange(x_min, x_max, x_step), np.arange(y_min, y_max, y_step))

# raise Exception(self.yy.ravel().shape)
Z = model.predict(np.c_[xx.ravel(), yy.ravel()])

ValueError: shapes (160000,2) and (8,3) not aligned: 2 (dim 1) != 8 (dim 0)