In [99]:
import yellowbrick

In [101]:
X = np.array([
     ("fox", '', 'brown', 'empty'),  
     ("fox", '', 'brown', ''),  
     ("fox", '', 'brown', 1.3),  
    ]
)


In [102]:
X.dtype

dtype('<U5')

In [103]:
np.where(isinstance(X, str))

(array([], dtype=int64),)

In [104]:
X.dtype

dtype('<U5')

In [105]:
np.issubdtype(X.dtype, np.string_) or np.issubdtype(X.dtype, np.unicode_)

True

In [89]:
np.core.defchararray.find(X, '')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [90]:
X

array([['fox', '', 'brown', 'empty'],
       ['fox', '', 'brown', ''],
       ['fox', '', 'brown', '1']], dtype='<U5')

In [91]:
np.flatnonzero(np.core.defchararray.find(X,'')!=-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [92]:
np.char.translate(X, str.maketrans({'o': 'i'}), 'i')

array([['fix', '', 'briwn', 'empty'],
       ['fix', '', 'briwn', ''],
       ['fix', '', 'briwn', '1']], dtype='<U5')

In [100]:
X.T

array([['fox', 'fox', 'fox'],
       ['', '', ''],
       ['brown', 'brown', 'brown'],
       ['empty', '', '1']], dtype='<U5')

In [96]:
Z.shape

(3, 4)

In [97]:
mask = np.where( X == '' )
Z = np.zeros(X.shape)
Z[mask] = np.nan

In [98]:
Z

array([[ 0., nan,  0.,  0.],
       [ 0., nan,  0., nan],
       [ 0., nan,  0.,  0.]])