In [8]:
%matplotlib inline

In [15]:
import warnings
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

from sklearn.model_selection import KFold, cross_val_score, ShuffleSplit, StratifiedKFold
from sklearn import datasets, svm, linear_model 

In [10]:
#When the cv argument is an integer, cross_val_score uses the KFold or StratifiedKFold 
#strategies by default, the latter being used if the estimator derives from ClassifierMixin.
#http://scikit-learn.org/stable/modules/cross_validation.html
#example 1 - using k_fold
digits = datasets.load_digits()
X_digits = digits.data
y_digits = digits.target
k_fold = KFold(n_splits=3)
svc = svm.SVC(C=1, kernel='linear')
cross_val_score(svc, X_digits, y_digits, cv=k_fold, n_jobs=-1)

array([ 0.93489149,  0.95659432,  0.93989983])

In [21]:
#example 2 - using int
iris = datasets.load_iris()
clf = svm.SVC(kernel='linear', C=1)
scores = cross_val_score(clf, iris.data, iris.target, cv=5)
scores   
print(len(scores))
xvals = range(1,len(scores),1)
print(xvals)

5
range(1, 5)


In [12]:
#example 3 - provide nothing
diabetes = datasets.load_diabetes()
X = diabetes.data[:150]
y = diabetes.target[:150]
lasso = linear_model.Lasso()
print(cross_val_score(lasso, X, y)) 

[ 0.33150734  0.08022311  0.03531764]


In [13]:
#It is also possible to use other cross validation strategies by passing a cross validation iterator instead, for instance:

n_samples = iris.data.shape[0]
cv = ShuffleSplit(n_splits=3, test_size=0.3, random_state=0)
cross_val_score(clf, iris.data, iris.target, cv=cv)

array([ 0.97777778,  0.97777778,  1.        ])

In [17]:
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([0, 0, 1, 1])
skf = StratifiedKFold(n_splits=2)
cross_val_score(clf, X, y, cv=skf)

array([ 0.5,  0.5])