In [1]:
%matplotlib inline

In [6]:
import warnings
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

from sklearn.model_selection import KFold, cross_val_score
from sklearn import datasets, svm, linear_model

In [3]:
#example 1 - using k_fold
digits = datasets.load_digits()
X_digits = digits.data
y_digits = digits.target
k_fold = KFold(n_splits=3)
svc = svm.SVC(C=1, kernel='linear')
cross_val_score(svc, X_digits, y_digits, cv=k_fold, n_jobs=-1)

array([ 0.93489149,  0.95659432,  0.93989983])

In [4]:
#example 2 - using int
iris = datasets.load_iris()
clf = svm.SVC(kernel='linear', C=1)
scores = cross_val_score(clf, iris.data, iris.target, cv=5)
scores   

array([ 0.96666667,  1.        ,  0.96666667,  0.96666667,  1.        ])

In [7]:
#example 3 - provide nothing
diabetes = datasets.load_diabetes()
X = diabetes.data[:150]
y = diabetes.target[:150]
lasso = linear_model.Lasso()
print(cross_val_score(lasso, X, y)) 

[ 0.33150734  0.08022311  0.03531764]
